FROM centos:7

# Set locale
RUN localedef -i en_US -f UTF-8 en_US.UTF-8
ENV LC_ALL en_US.utf8
ENV LANG en_US.UTF-8
ENV PYTHONIOENCODING utf-8

# Install Docker
RUN yum -y install yum-utils
RUN yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
RUN yum -y install python3 python3-pip python3-devel docker-ce docker-ce-cli containerd.io
RUN yum -y groupinstall 'Development Tools'
RUN yum clean all

# Add python build requirements
RUN python3 -m pip install --upgrade pip setuptools wheel
COPY build-requirements.txt /tmp/build-requirements.txt
RUN pip install --no-cache-dir -r /tmp/build-requirements.txt
